	CREATE TABLE IF NOT EXISTS users(
	id serial PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS habits(
	id serial PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	name VARCHAR(100) NOT NULL,
	description TEXT,
	start_date DATE NOT NULL DEFAULT CURRENT_DATE,
	current_streak INTEGER DEFAULT 0,
	longest_streak INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS habits_checkins(
	id SERIAL PRIMARY KEY,
	habit_id INTEGER REFERENCES habits(id) ON DELETE CASCADE,
	checkin_date DATE NOT NULL DEFAULT CURRENT_DATE
);